### PR TITLE
Modernize Python 2 code to get ready for Python 3

### PR DESCRIPTION
**Pull request by cclauss**
* Use __print()__ function in both Python 2 and Python 3
    * Legacy __print__ statements are syntax errors in Python 3 but __print()__ function works as expected in both Python 2 and Python 3.
* Old style exceptions --> new style for Python 3
    * Old style exceptions are syntax errors in Python 3 but new style exceptions work as expected in both Python 2 and Python 3.
* Use __exec()__ function in both Python 2 and Python 3
    * __exec()__ is a function in Python 3.

### CODE REVIEW

**Comment by LiuChangFreeman** [comment]
This patch does not work well with IronPython. I will consider modernizing the Python 2 code after this problem is solved.

**Comment by cclauss** [comment]
Which file(s) does IronPython complain about?  What error message(s) does it generate?

**Comment by LiuChangFreeman** [comment]
> Which file(s) does IronPython complain about? What error message(s) does it generate?

1. Remove the exception handler in "编译器\编译器\MainWindow.xaml.cs" 
2. Click the first and second button
3. IronPython will exec the Python Code and throw a exception "Can only register classes"  

screenshot

**Comment by cclauss** [comment]
Closing in favor of #2 and #3.

**Pull request closed without merging**
